---
title: "Data exploration Airbnb Valentine's Day"
output:
  pdf_document: default
  html_document: default
date: "2022-09-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, include=FALSE}
# Load packages
library(dplyr)
library(tidyverse)
library(scales)
```

```{r, echo=FALSE}
# Load data
list_par <- read.csv(gzfile('../../data/listings-paris.csv.gz'))
list_rom <- read.csv(gzfile('../../data/listings-rome.csv.gz')) 
list_mad <- read.csv(gzfile('../../data/listings-madrid.csv.gz'))
```

```{r}
summary(list_mad$beds)
summary(list_mad$room_type)
summary(list_mad$price)
summary(list_par$beds)
summary(list_par$room_type)
summary(list_par$price)
summary(list_rom$beds)
summary(list_rom$room_type)
summary(list_rom$price)
```

```{r, echo=FALSE}
subset_list_mad <- data.frame(
  id = list_mad$id,
  name = list_mad$name,
  room_type = list_mad$room_type,
  city = "Madrid"
)

subset_list_par <- data.frame(
  id = list_par$id,
  name = list_par$name,
  room_type = list_par$room_type,
  city = "Paris"
)

subset_list_rom <- data.frame(
  id = list_rom$id,
  name = list_rom$name,
  room_type = list_rom$room_type,
  city = "Rome"
)

total_list <- rbind(subset_list_mad, subset_list_par, subset_list_rom)
```

**Number of rooms per city**
```{r, echo=FALSE}
table(total_list$room_type, total_list$city)
```

**Percentage number of rooms in Madrid**
```{r, echo=FALSE}
madrid <- table(list_mad$room_type)
prop.table(madrid)
```

**Percentage number of rooms in Paris**
```{r, echo=FALSE}
paris <- table(list_par$room_type)
prop.table(paris)
```

**Percentage number of rooms in Rome**
```{r, echo=FALSE}
rome <- table(list_rom$room_type)
prop.table(rome)
```

```{r, echo=FALSE}
# Basic piechart
piepercent_mad<- round(100*table(list_mad$room_type)/sum(table(list_mad$room_type)), 1)

pie(table(list_mad$room_type), labels = paste0(piepercent_mad, "%"), main = "Madrid pie chart", col = rainbow(length(table(list_mad$room_type)), s = 0.5))
legend("topright", c("Entire home/apt","Hotel room","Private room","Shared room"), cex = 0.8,
       fill = rainbow(length(table(list_mad$room_type)), s = 0.5))
```

```{r, echo=FALSE}
# Basic piechart
piepercent_par<- round(100*table(list_par$room_type)/sum(table(list_par$room_type)), 1)

pie(table(list_par$room_type), labels = paste0(piepercent_par, "%"), main = "Paris pie chart", col = rainbow(length(table(list_par$room_type)), s = 0.5))
legend("topright", c("Entire home/apt","Hotel room","Private room","Shared room"), cex = 0.8,
       fill = rainbow(length(table(list_par$room_type)), s = 0.5))
```

```{r, echo=FALSE}
# Basic piechart
piepercent_rom<- round(100*table(list_rom$room_type)/sum(table(list_rom$room_type)), 1)

pie(table(list_rom$room_type), labels = paste0(piepercent_rom, "%"), main = "Rome pie chart", col = rainbow(length(table(list_rom$room_type)), s = 0.5))
legend("topright", c("Entire home/apt","Hotel room","Private room","Shared room"), cex = 0.8,
       fill = rainbow(length(table(list_rom$room_type)), s = 0.5))
```

```{r, echo=FALSE}
# Frequency Bar Graph
ggplot(list_mad, aes(x = room_type)) +
    geom_bar(aes(fill = room_type), position = "dodge") +
    ggtitle("Madrid") +
    theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Type of room", y = "Number of rooms", fill = "Type of room") +
    scale_fill_viridis_d()
ggplot(list_par, aes(x = room_type)) +
    geom_bar(aes(fill = room_type), position = "dodge") +
    ggtitle("Paris") +
    theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Type of room", y = "Number of rooms", fill = "Type of room") +
    scale_fill_viridis_d()
ggplot(list_rom, aes(x = room_type)) +
    geom_bar(aes(fill = room_type), position = "dodge") +
    ggtitle("Rome") +
    theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Type of room", y = "Number of rooms", fill = "Type of room") +
    scale_fill_viridis_d()
```


```{r, echo=FALSE}
# Percentage/Proportion Bar Graph
ggplot(list_mad, aes(x = room_type)) +
    geom_bar(aes(y = (..count..)/sum(..count..), fill = room_type), position = "dodge") +
    ggtitle("Madrid") +
    theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Type of room", y = "Number of rooms", fill = "Type of room") +
    scale_fill_viridis_d() +
    scale_y_continuous(labels = scales::percent_format(), name = "Percentage of rooms")
ggplot(list_par, aes(x = room_type)) +
    geom_bar(aes(y = (..count..)/sum(..count..), fill = room_type), position = "dodge") +
    ggtitle("Paris") +
    theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Type of room", y = "Number of rooms", fill = "Type of room") +
    scale_fill_viridis_d() +
    scale_y_continuous(labels = scales::percent_format(), name = "Percentage of rooms")
ggplot(list_rom, aes(x = room_type)) +
    geom_bar(aes(y = (..count..)/sum(..count..), fill = room_type), position = "dodge") +
    ggtitle("Rome") +
    theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "Type of room", y = "Number of rooms", fill = "Type of room") +
    scale_fill_viridis_d() +
    scale_y_continuous(labels = scales::percent_format(), name = "Percentage of rooms")
```

```{r, echo=FALSE}
ggplot(total_list, aes(x = room_type)) +
    geom_bar(aes(fill = room_type), position = "dodge") +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank()) +
    facet_grid(~city) +
    labs(x = "Type of room", y = "Number of rooms", fill = "Type of room") +
    scale_fill_viridis_d()
```
