####################
## PRICE ANALYSIS ##
####################

# Create directory for output generated by analysis #
dir.create('../../gen/analysis/output', recursive = T)

# Load libraries #
library(ggplot2)
library(tidyverse)
library(ggpubr)

## INPUT ##
complete_data <- read.csv("../../gen/data-preparation/temp/complete_data.csv") 

# Descriptive statistics price #
summary(complete_data$price)
mean_price <- mean(complete_data$price)
save(mean_price, file = 'meanprice.RData')

table(complete_data$price)
histogram_prices <- hist(complete_data$price, xlab = 'price in €') 

# Descriptives Valentine's day #
summary(complete_data$valentinesday)
mean_valentinesday <- mean(complete_data$valentinesday)
save(mean_valentinesday, file = 'meanvalentinesday.RData')

valentinesday_yes_no <- table(complete_data$valentinesday)

# Assumptions (normality and outliers) #
set.seed(5000)
complete_data_sample <- rnorm(5000)
shapiro.test(complete_data_sample)

shapiro_test_pvalue <- shapiro.test(complete_data_sample)$p.value
save(shapiro_test_pvalue, file = 'shapiropvalue.RData')

# Visualization of assumptions #
price_valentinesday_boxplot <- ggboxplot(complete_data, x="valentinesday", y="price",
                                         color="valentinesday", palette = c("#00AFBB", "#E7B800"),
                                         ylab= "Price", xlab="Valentinesday")

# T-test for price #
# Price in total 
t_test_price <- t.test(price ~ valentinesday, complete_data) 
ttest_pvalue <- t_test_price$p.value
save(ttest_pvalue, file = 'ttestpvalue.RData')

# Price per city 
price_per_city <- lapply(split(complete_data, factor(complete_data$city)), function(x)t.test(data=x, price ~ valentinesday, paired=FALSE))
pvalue_madrid <- price_per_city$Madrid$p.value
save(pvalue_madrid, file = 'pvaluemardrid.RData')
pvalue_paris <- price_per_city$Paris$p.value
save(pvalue_paris, file = 'pvalueparis.RData')
pvalue_rome <- price_per_city$Rome$p.value
save(pvalue_rome, file = 'pvaluerome.RData')

# Visualization #
# Plot for different cities 
boxplot_price_per_city <- ggplot(complete_data, aes(x=valentinesday, y=price, fill=city)) + 
    geom_boxplot() +
    facet_wrap(~valentinesday, scale="free") +
    theme(axis.text.x=element_blank(),
          axis.ticks.x=element_blank())

## OUTPUT ##
write.csv(valentinesday_yes_no, '../../gen/analysis/output/valentinesday_yes_no.csv')
ggsave(plot = price_valentinesday_boxplot, filename = "../../gen/analysis/output/price_valentinesday_boxplot.pdf")
pdf(file="../../gen/analysis/output/histogram_prices.pdf")
dev.off()
ggsave(plot = boxplot_price_per_city, filename = "../../gen/analysis/output/boxplot_price_per_city.pdf")
